// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpotList struct {
	_tab flatbuffers.Table
}

func GetRootAsSpotList(buf []byte, offset flatbuffers.UOffsetT) *SpotList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpotList{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSpotList(buf []byte, offset flatbuffers.UOffsetT) *SpotList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SpotList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SpotList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpotList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpotList) Spot(obj *Spot, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SpotList) SpotLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SpotListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SpotListAddSpot(builder *flatbuffers.Builder, spot flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(spot), 0)
}
func SpotListStartSpotVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SpotListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
